version: 0.2

phases:
  install:
    runtime-versions:
       golang: 1.x
  pre_build:
    commands:
      - go mod tidy
  build:
    commands:
      - sh build_booklist.sh
  post_build:
    commands:
      - aws lambda update-function-code --function-name books_list --zip-file fileb://lambda/lambda_getlist/list.zip
